### ISSUE TITLE
Run Test

### ISSUE THREAD

**Issue by Dan-Amaral** [Dan-Amaral/Rail-View#2]
Hi Max, when I tried to run the last part for see the project (Number 4 - the test yarn build (or npm run build). It compiles app into /dist.) I have the following error ::

'cp' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I tried the npm also, but didn't work too. Do you know the probable cause of this?

**Comment by Maxgrb** [comment]
@Dan-Amaral update, now it should work.

**Comment by Dan-Amaral** [comment]
Ah, sorry @Maxgrb , I forgot about the "@" last time, my bad. I have both of them in my machine, but I'm trying with windows now.

But, I tried with your new version and I get again one error:

$ yarn && NODE_ENV=production webpack
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Maxgrb** [comment]
@Dan-Amaral remove `package-lock.json` and try now.

**Comment by Dan-Amaral** [comment]
Perfect, now it works! Thanks @Maxgrb !

**Comment by Maxgrb** [comment]
@Dan-Amaral cool!
