### ISSUE TITLE
Version 0.0.2

### ISSUE THREAD

**Issue by Dan-Amaral** [Dan-Amaral/Rail-View#3]
Hi @Maxgrb I talked with Robert last friday about some improvements in the front-end, you already finished it? Because I tried to run your new version and I receive this error : 

ERROR in ./app/components/index.js
Module Error (from ./node_modules/eslint-loader/index.js):

C:\Users\danie\MAX_V2\Rail-View-master\app\components\index.js
  15:36  error  Casing of ./Toolbar does not match the underlying filesystem  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)

 @ ./app/index.js 17:18-43
 @ ./index.js

ERROR in ./app/components/index.js
Module not found: Error: [CaseSensitivePathsPlugin] `C:\Users\danie\MAX_V2\Rail-View-master\app\components\Toolbar\index.js` does not match the corresponding path on disk `ToolBar`.
 @ ./app/components/index.js 106:15-35
 @ ./app/index.js
 @ ./index.js

I tried with yarn and in windows, like the last time

**Comment by Dan-Amaral** [comment]
@Maxgrb still the same error.

**Comment by Maxgrb** [comment]
@Dan-Amaral and now?

**Comment by Dan-Amaral** [comment]
@Maxgrb now, all good!

**Comment by Dan-Amaral** [comment]
And about the tow new features, how much time do you think is gonna take? @Maxgrb

**Comment by Dan-Amaral** [comment]
The two next ones, measurement tool and annotation tool

**Comment by Maxgrb** [comment]
@Dan-Amaral do you mean when I can deliver it or how many hours it'll take to implement?

**Comment by Dan-Amaral** [comment]
When you can deliver. Just one estimation

**Comment by Maxgrb** [comment]
Depends on my workload. Possible, annotations by the end of the week. Measurement – the next week
